[package]
name = "yyyoink_desktop"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.13.1", features = ["tokio"] }
tokio = { version = "1.44.2", features = ["fs", "io-util"] }
palette = "0.7.4"
